development: &development
  host: 127.0.0.1
  user: root
  password:
  database: license_server
  charset: utf8_general_ci
  timezone: UTC

test:
  <<: *development
  database: license_server_test

  # TODO ssl connection for staging and production